---
- name: Provision Summit Balloon Game
  hosts: local

  vars_files:
    - vars/game-config.yml

  roles:
  - setup-achievement-server
  - setup-score-server
  - setup-game-server
  - setup-game-app
  - setup-admin-app
  - setup-scoreboard-app
  - setup-leaderboard-app
  - {role: wait-client-apps, when: parallel_build}  
  - setup-cicd
  
  pre_tasks:

    - name: Login to openshift as admin
      command: "oc login --insecure-skip-tls-verify=true -u {{admin_username}} -p {{admin_password}} {{master_url}}"

    - name: Install ephemeral postgresSQL template
      command: "oc apply -f https://raw.githubusercontent.com/luciddreamz/library/master/official/postgresql/templates/postgresql-ephemeral.json -n openshift"
      ignore_errors: true

    - name: Install Jboss Image Streams
      command: "oc apply -f https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.7/xpaas-streams/jboss-image-streams.json -n openshift"
      ignore_errors: true

    - name: Install BRMS ImageStream
      command: "oc apply -f https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-streams/decisionserver64-image-stream.json -n openshift"
      ignore_errors: true

    - name: Install BRMS template
      command: "oc apply -f https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-templates/decisionserver64-basic-s2i.json -n openshift"
      ignore_errors: true

    - name: Install Java S2I ImageStream
      command: "oc apply -f https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.9/roles/openshift_examples/files/examples/v3.9/xpaas-streams/openjdk18-image-stream.json -n openshift"
      ignore_errors: true

    - name: Login to openshift as user
      command: "oc login --insecure-skip-tls-verify=true -u {{username}} -p {{password}} {{master_url}}"

    - name: Create openshift project
      command: "oc new-project {{project_name}} --display-name='Summit Balloon Game' --description='Multiplayer mobile balloon game from 2016 Red Hat Summit'"

    - name: Create authentication token secret
      command: "oc create secret generic game-auth --from-literal=token={{auth_token}}"

    # - name: Add view role to support kubernetes discovery for system:serviceaccounts:summit-game group
    #   command: "oc policy add-role-to-group view system:serviceaccounts:{{project_name}} -n {{project_name}}"
    #   ignore_errors: true

    - name: Update default service account to enable kube API access for infinispan clustering
      shell: "oc policy add-role-to-user view system:serviceaccount:$(oc project -q):default -n $(oc project -q)"

    - name: Set empty Maven Mirror variable
      set_fact: 
        maven_mirror_url: ""
      when: maven_mirror_url is not defined
