---
# Create single build for both blue/green rather then separate apps
- name: Create gamebus buildconfig
  shell: "oc process -p APPLICATION_NAME=gamebus -p SOURCE_REPOSITORY_URL={{ game_server_repo }} -p MAVEN_MIRROR_URL={{maven_mirror_url}} -f roles/setup-game-server/files/game-server-build.json | oc create -f -"

- name: Start gamebus build and wait
  command: "oc start-build gamebus --wait=true"

- name: Tag gamebus imagestream for colors
  shell: |
    oc tag {{project_name}}/gamebus:latest {{project_name}}/gamebus:green
    oc tag {{project_name}}/gamebus:latest {{project_name}}/gamebus:blue
    oc tag {{project_name}}/gamebus:latest -d

- name: Create blue game server
  command: "oc new-app -f roles/setup-game-server/files/game-server-template.json -p COLOR=blue -p APPLICATION_NAME=gamebus -p REPLICA_COUNT={{gamebus_replica_count}} -p NAMESPACE={{project_name}} -p SCORE_USERNAME={{score_user}} -p SCORE_PASSWORD={{score_password}}"

- name: Create green game server
  command: "oc new-app -f roles/setup-game-server/files/game-server-template.json -p COLOR=green -p APPLICATION_NAME=gamebus -p REPLICA_COUNT={{gamebus_replica_count}} -p NAMESPACE={{project_name}} -p SCORE_USERNAME={{score_user}} -p SCORE_PASSWORD={{score_password}}"

- name: Wait for blue game server to be ready
  command: "oc get ep gamebus-blue"
  register: result
  until: result.stdout.find("none") == -1 
  retries: 50
  delay: 10

- name: Wait for green game server to be ready
  command: "oc get ep gamebus-green"
  register: result
  until: result.stdout.find("none") == -1 
  retries: 50
  delay: 10

- name: Create gamebus blue-green routes
  shell: |
    oc process -p APPLICATION_NAME=gamebus -f roles/setup-game-server/files/game-server-routes.json | oc create -f -
    oc annotate route/gamebus haproxy.router.openshift.io/balance=roundrobin
    oc annotate route/gamebus haproxy.router.openshift.io/disable_cookies=true